name: Init

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Optimise Network Settings
        run: |
            sudo sysctl -w net.core.default_qdisc=fq
            sudo sysctl -w net.ipv4.tcp_congestion_control=bbr
            sudo sysctl -w net.ipv4.tcp_window_scaling=1
            sudo sysctl -w net.ipv4.ip_forward=1
            sudo sysctl -w net.ipv4.tcp_ecn=1
            sudo sysctl -w net.ipv4.tcp_ecn_fallback=1
            sudo sysctl -w net.core.rmem_max=25000000
            sudo sysctl -p

      - name: Install Deps
        run: |
            sudo add-apt-repository ppa:apt-fast/stable
            sudo apt-get clean all
            sudo apt-get update
            sudo apt-get install -y apt-fast
            sudo cp -f ./apt-fast.conf /var/cache/apt/archives/
            sudo apt-get install -y wget unzip ffmpeg python3-pip git curl libcurl4-openssl-dev aria2
            sudo python3 -m pip install -U yt-dlp

      - name: Set Permissions
        run: |
            sudo unzip ./1x.zip
            sudo chmod -R 777 ./1w2x
            sudo chmod -R 777 ./wgcf
            sudo mv katheryne 1x
            sudo chmod -R 777 ./1x
            sudo chmod -R 777 ./w2x
            sudo chmod -R 777 ./magick
            sudo chmod -R 777 ./resrgan/resrgan
            sudo mkdir ./cache/
            sudo chmod -R 777 ./cache/
            sudo mkdir ./img/
            sudo chmod -R 777 ./img/
            sudo chmod -R 777 ./models-cunet/
            sudo chmod -R 777 ./models-upconv_7_anime_style_art_rgb/
            sudo chmod -R 777 ./models-upconv_7_photo/

      - uses: actions/setup-go@v2
        with:
            go-version: '^1.18'
      - run: |
            go version

      - name: Init
        run: |
            sudo pwd
            sudo unzip ./cf.zip
            sudo dpkg -i ./cf/cf.deb
            sudo mkdir /root/.cloudflared/
            sudo chmod -R 777 /root/.cloudflared/
            sudo cp ./cf/2ff8bbb1-43db-48fb-996c-469104621104.json /root/.cloudflared/
            sudo cp ./cf/ae43fbca-c534-4e91-99af-ee0262fd7027.json /root/.cloudflared/
            sudo cp ./cf/cert.pem /root/.cloudflared/
            sudo cp ./cf/config.yml /root/.cloudflared/
            sudo rm -rf /etc/cloudflared/config.yml

      - name: Aria2
        run: |
            sudo git clone https://github.com/ziahamza/webui-aria2.git
            sudo chmod -R 777 ./webui-aria2
            sudo aria2c --enable-rpc --rpc-listen-all --rpc-listen-port=443 &

      - name: Front-end (start cf)
        run: |
            sudo cloudflared tunnel cleanup 2ff8bbb1-43db-48fb-996c-469104621104
            sudo cloudflared service install
            sudo service cloudflared start
            sudo cloudflared tunnel run 2ff8bbb1-43db-48fb-996c-469104621104 &

      - name: Sleep for 5s
        uses: juliangruber/sleep-action@v1
        with:
          time: 5s

      - name: Back-end
        continue-on-error: true
        timeout-minutes: 310
        run: ./1x

      - name: Front-end (stop cf)
        run: |
            sudo service cloudflared stop
            sudo cloudflared tunnel cleanup 2ff8bbb1-43db-48fb-996c-469104621104
            sudo cloudflared service uninstall

      - name: Always Check
        if: always()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          event-type: restart
          client-payload: '{"runid": "${{ github.run_id }}"}'
